#! /bin/csh -f

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/
cp -f gdb-10.2.mcore-elf/sim/mcore/mine.cpp ~/lang/53_GNU_tool/gcc_cross/MCORE/memory/mine.cpp
cp -f gdb-10.2.mcore-elf/sim/mcore/Makefile ~/lang/53_GNU_tool/gcc_cross/MCORE/memory/Makefile.mine
diff -c gdb-10.2.{org,mcore-elf}/sim/common/sim-load.c > ~/lang/53_GNU_tool/gcc_cross/MCORE/memory/memory.diff
diff -c gdb-10.2.{org,mcore-elf}/sim/mcore/interp.c >> ~/lang/53_GNU_tool/gcc_cross/MCORE/memory/memory.diff
