%.o : %.S
	d30v-elf-as -o $@ -g $<

%.o : %.c
	d30v-elf-gcc -o $@ $< -c -g

%.elf : %.o 
	d30v-elf-ld -o $@ ../default.o $< -T ../default.x

%.objdump : %.elf
	d30v-elf-objdump -x -d -g $< > $@

%.log : %.elf
	wdog.exe -v d30v-elf-gdb -q -x gdbcom $< > $@

%.lof : %.log
	wdog.exe -v diff $< $@
	touch $@

clean:
	rm -f *.o *.s *.elf *.map *.objdump *.log TAGS *~

