%.o : %.S
	mn10300-elf-as -o $@ $< -g

%.o : %.c
	mn10300-elf-gcc -o $@ $< -c -g

LIBGCC = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/mn10300-elf/10.2.0/libgcc.a

%.elf : %.o
	mn10300-elf-ld -o $@ start.o $< $(LIBGCC) -T $(basename $<).x

%.objdump : %.elf
	mn10300-elf-objdump -x -d -g $< > $@

%.log : %.elf
	wdog.exe -v mn10300-elf-gdb -q -x gdbcom $< > $@

%.lof : %.log
	wdog.exe -v diff $< $@
	touch $@

clean:
	rm -f *.s *.o *.elf *.objdump *.log *.a *.map *~

