#! /bin/csh -vf

ft32-elf-as -o start.o --no-relax -g start.S || exit 1
ft32-elf-gcc -o sample.s sample.c -S || exit 1
ft32-elf-as -o sample.o --no-relax -g sample.s || exit 1
ft32-elf-ld -o sample.elf start.o sample.o /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/ft32-elf/10.2.0/libgcc.a -T sample.x || exit 1
ft32-elf-objdump -x -d sample.elf > sample.objdump || exit 1
ft32-elf-run --memory-region 0x80e000,0x1000 sample.elf
