%.o : %.S
	h8300-elf-as -o $@ $< -g

%.o : %.c
	h8300-elf-gcc -o $@ $< -g -c

LIBGCC = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/h8300-elf/10.2.0/libgcc.a
LIBC = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/h8300-elf/lib/libc.a

%.elf : %.o
	h8300-elf-ld -o $@ ../default.o $< $(LIBC) $(LIBGCC) -T ../default.x

%.objdump : %.elf
	h8300-elf-objdump -x -t -d -g $< > $@

%.log : %.elf
	wdog.exe -v h8300-elf-gdb -q -x gdbcom $< > $@

%.lof : %.log
	wdog.exe -v diff $< $@
	touch $@

clean:
	rm -f *.s *.o *.elf *.map *.objdump *.log *~
