all:test000.elf test000.objdump

test000_start.o:test000_start.S
	avr-elf-as -g -o $@ $<

#test000.o:test000.s
#	avr-elf-as -g -o $@ $<
#
#test000.s:test000.c
#	avr-elf-gcc -S -o test000.s test000.c

test000.o:test000.c
	avr-elf-gcc -g -c -o test000.o test000.c

test000.elf:test000_start.o test000.o
	avr-elf-ld -o test000.elf test000_start.o test000.o -Map test000.map

test000.objdump:test000.elf
	avr-elf-objdump -x -d test000.elf > test000.objdump

clean:
	rm -f test000_start.o test000.o test000.s test000.elf test000.map
	rm -f test000.objdump *~
