all:hello.objdump

start.o:start.S
	m68hc11-elf-as -o start.o -g start.S

hello.o:hello.c
	m68hc11-elf-gcc -o hello.o -g -c hello.c

#hello.s:hello.c
#	m68hc11-elf-gcc -o hello.s -S hello.c
#
#hello.o:hello.s
#	m68hc11-elf-as -o hello.o -g hello.s

dummy.o:dummy.c
	m68hc11-elf-gcc -o dummy.o -g -c dummy.c

#dummy.s:dummy.c
#	m68hc11-elf-gcc -o dummy.s -S dummy.c
#
#dummy.o:dummy.s
#	m68hc11-elf-as -o dummy.o -g dummy.s

LIBC = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/m68hc11-elf/lib/libc.a

LIBGCC = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/m68hc11-elf/3.4.4/libgcc.a

hello.elf:start.o hello.o dummy.o hello.x
	m68hc11-elf-ld -o hello.elf start.o hello.o dummy.o \
	$(LIBC) $(LIBGCC) -T hello.x -Map hello.map

hello.objdump:hello.elf
	m68hc11-elf-objdump -x -d hello.elf > hello.objdump

clean:
	rm -f *.s *.o *.elf *.map *.objdump *~
