%.o : %.S
	riscv-elf-as -o $@ -g $<

%.t : %.c
	riscv-elf-gcc -o $@ $< -g -S

%.s : %.t
	sed -e '/attribute arch/d' $< > $@

%.o : %.s
	riscv-elf-as -o $@ $<

%.elf : %.o 
	riscv-elf-ld -o $@ ../default.o $< -T ../default.x

%.objdump : %.elf
	riscv-elf-objdump -x -d -g $< > $@

%.log : %.elf
	wdog.exe -v riscv-elf-gdb -q -x gdbcom $< > $@

%.lof : %.log
	wdog.exe -v diff $< $@
	touch $@

clean:
	rm -f *.o *.s *.t *.elf *.map *.objdump *.objcopy *.log TAGS *~
