#! /bin/csh -vf

arm-elf-as -o start.o -g start.S || exit 1
#arm-elf-gcc -o sample.o -g sample.c -c || exit 1
arm-elf-gcc -o sample.s sample.c -S || exit 1
arm-elf-as -o sample.o sample.s -g || exit 1
arm-elf-ld -o sample.elf start.o sample.o /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/arm-elf/10.2.0/libgcc.a -T sample.x || exit 1
arm-elf-objdump -x -d sample.elf > sample.objdump || exit 1
arm-elf-run --memory-region 0x1b000,0x5000 sample.elf
