%.o : %.S
	mmix-elf-as -o $@ -g -no-predefined-syms -x $<

%.o : %.c
	mmix-elf-gcc -o $@ $< -c -g

%.elf : %.o 
	export GNUTARGET=elf64-mmix ; mmix-elf-ld -o $@ ../default.o $< -T ../default.x

%.objdump : %.elf
	mmix-elf-objdump -x -d -g $< > $@

%.log : %.elf
	wdog.exe -v mmix-elf-gdb -q -x gdbcom $< > $@

%.lof : %.log
	wdog.exe -v diff $< $@
	touch $@

clean:
	rm -f *.o *.s *.elf *.map *.objdump *.log TAGS *~

