#! /bin/csh -vxf

sh64-elf-as -o test.o -g test.S --isa=sh2 || exit 1
sh64-elf-ld -o test.elf test.o -T ../default.x || exit 1
sh64-elf-objdump -x -d -g test.elf > test.objdump || exit 1
sh64-elf-gdb -q -x gdbcom test.elf
