#! /bin/csh -vf

sh-elf-as -o start.o -g start.S || exit 1
sh-elf-gcc -o sample.o -g sample.c -c || exit 1
sh-elf-ld -o sample.elf start.o sample.o /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/sh-elf/10.2.0/libgcc.a -T sample.x || exit 1
sh-elf-objdump -x -d sample.elf > sample.objdump
sh-elf-run sample.elf
