#! /bin/csh -vf

sparc-elf-as -o start.o -g start.S || exit 1
sparc-elf-gcc -o sample.s sample.c -S || exit 1
sparc-elf-as -o sample.o -g sample.s || exit 1
#sparc-elf-gcc -o sample.o sample.c -g -c || exit 1
sparc-elf-ld -o sample.elf start.o sample.o -T sample.x || exit 1
sparc-elf-objdump -x -d sample.elf > sample.objdump || exit 1
sparc-elf-run --memory-fill 0xcc --memory-region 0x1b000,0x5000 sample.elf

