#! /bin/csh -vxf

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG
cp -f gdb-10.2.rl78-elf.new/sim/rl78/Makefile.mine ~/lang/53_GNU_tool/gcc_cross/RL78/memory/Makefile.mine
diff -c gdb-10.2.rl78-elf{,.new}/sim/common/sim-load.c > ~/lang/53_GNU_tool/gcc_cross/RL78/memory/memory.diff
foreach file (cpu.c gdb-if.c mem.c rl78.c)
  diff -c gdb-10.2.rl78-elf{,.new}/sim/rl78/$file >> ~/lang/53_GNU_tool/gcc_cross/RL78/memory/memory.diff
end
