#! /bin/csh -vf

i960-elf-as -o start.o --gstabs start.S || exit 1
i960-elf-gcc -o sample.s sample.c -S || exit 1
i960-elf-as -o sample.o sample.s --gstabs || exit 1
i960-elf-ld -o sample.elf start.o sample.o -T sample.x || exit 1
i960-elf-objdump -x -d sample.elf > sample.objdump || exit 1
i960-elf-run --memory-fill 0xcc --memory-region 0x1b000,0x5000 sample.elf

