#! /bin/csh -vf

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG
diff -c gdb-10.2.org/sim/common/sim-load.c gdb-10.2.h8300-elf/sim/common/sim-load.c > ~/lang/53_GNU_tool/gcc_cross/H8/mem_acc/sim-load.diff
diff -c gdb-10.2.org/sim/h8300/compile.c gdb-10.2.h8300-elf/sim/h8300/compile.c > ~/lang/53_GNU_tool/gcc_cross/H8/mem_acc/compile.diff
diff -c gdb-10.2.{org,h8300-elf}/gdb/h8300-tdep.c > ~/lang/53_GNU_tool/gcc_cross/H8/mem_acc/h8300-tdep.diff
cp -f gdb-10.2.h8300-elf/sim/h8300/my_cache.cpp ~/lang/53_GNU_tool/gcc_cross/H8/mem_acc/my_cache.cpp
