#! /bin/csh -vf

loongarch64-elf-as -o start.o -g start.S || exit 1
loongarch64-elf-gcc -o sample.s sample.c -S || exit 1
loongarch64-elf-as -o sample.o -g sample.s || exit 1
loongarch64-elf-ld -o sample.elf start.o sample.o -T sample.x || exit 1
loongarch64-elf-objdump -x -d -g sample.elf > sample.objdump || exit 1
loongarch64-elf-run --memory-fill 0xcc --memory-region 0x1b000,0x5000 sample.elf
