#! /bin/csh -f

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/
diff -c gdb-10.2.{org,iq2000-elf}/sim/common/sim-load.c > ~/lang/53_GNU_tool/gcc_cross/IQ2000/memory/sim-load.diff
cp gdb-10.2.iq2000-elf/sim/iq2000/mine.cpp ~/lang/53_GNU_tool/gcc_cross/IQ2000/memory/
cp gdb-10.2.iq2000-elf/sim/iq2000/Makefile ~/lang/53_GNU_tool/gcc_cross/IQ2000/memory/Makefile.mine
