#! /bin/csh -f

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/
diff -c gdb-10.2.{org,microblaze-elf}/gdb/microblaze-tdep.c > ~/lang/53_GNU_tool/gcc_cross/MicroBlaze/microblaze-tdep.diff
