#! /bin/csh -vf

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG
diff -c gdb-10.2.{org,arm-elf}/sim/arm/wrapper.c > ~/lang/53_GNU_tool/gcc_cross/ARM/memory/memory.diff
diff -c gdb-10.2.{org,arm-elf}/sim/arm/armos.c >> ~/lang/53_GNU_tool/gcc_cross/ARM/memory/memory.diff
diff -c gdb-10.2.{org,arm-elf}/sim/arm/armvirt.c >> ~/lang/53_GNU_tool/gcc_cross/ARM/memory/memory.diff
diff -c gdb-10.2.{org,arm-elf}/sim/common/sim-load.c >> ~/lang/53_GNU_tool/gcc_cross/ARM/memory/memory.diff
cp -f gdb-10.2.arm-elf/sim/arm/mine.cpp ~/lang/53_GNU_tool/gcc_cross/ARM/memory//mine.cpp
cp -f gdb-10.2.arm-elf/sim/arm/sim-main.h ~/lang/53_GNU_tool/gcc_cross/ARM/memory/sim-main.h
cp -f gdb-10.2.arm-elf/sim/arm/Makefile ~/lang/53_GNU_tool/gcc_cross/ARM/memory/Makefile.mine

