all:test014.objdump test014.lof

include ../Makefile.common

test014.elf:test014.o test014.x start.o



#	ft32-elf-ld -o $@ start.o $< -T /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/ft32-elf/lib/ldscripts/elf32ft32.x --defsym stack=0xf000

test014.lof:test014.log
