%.o : %.S
	1750a-elf-as -o $@ -g $<

%.o : %.s
	1750a-elf-as -o $@ -g $<

CC1 = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/gcc-10.2.0.1750a-elf.mine/host-i686-pc-linux-gnu/gcc/cc1

%.s : %.c
	$(CC1) -o $@ $< -quiet -g

%.elf : %.o 
	1750a-elf-ld -o $@ ../default.o $< -T ../default.x

%.objdump : %.elf
	1750a-elf-objdump -x -d -g $< > $@

%.log : %.elf
	wdog.exe -v 1750a-elf-gdb -q -x gdbcom $< > $@

%.lof : %.log
	wdog.exe -v diff $< $@
	touch $@

clean:
	rm -f *.o *.s *.elf *.map *.objdump *.objcopy *.log TAGS *~
