#! /bin/csh -f

gcc -g3 a.c -c -o a.o || exit 1
gcc -g3 b.c -c -o b.o || exit 1
ar r test028.a a.o b.o || exit 1
../mktags.exe test028.a || exit 1
diff tags tags.exp || exit 1
../mktags.exe -e test028.a || exit 1
diff TAGS TAGS.e || exit 1
