#! /bin/csh -vxf

z80-elf-as -o start.o -g start.S || exit 1
z80-elf-gcc -o sample.s sample.c -S || exit 1
z80-elf-as -o sample.o -g sample.s || exit 1
z80-elf-ld -o sample.elf start.o sample.o -T sample.x || exit 1
z80-elf-objdump -x -d sample.elf > sample.objdump || exit 1
z80-elf-run --memory-fill 0xcc --memory-region 0xdff0,0x2000 sample.elf
