#! /bin/csh -vf

ns32k-elf-as -o start.o -g start.S || exit 1
ns32k-elf-gcc -o sample.s sample.c -S || exit 1
ns32k-elf-as -o sample.o -g sample.s || exit 1
ns32k-elf-ld -o sample.elf start.o sample.o -T sample.x || exit 1
ns32k-elf-objdump -x -d -g sample.elf > sample.objdump || exit 1
ns32k-elf-run --memory-fill 0xcc --memory-region 0x1b00,0x500 sample.elf
