#! /bin/csh -vf

mips-elf-as -o start.o  --gen-debug  start.S || exit 1
mips-elf-gcc -o sample.s sample.c -S || exit 1
mips-elf-as -o sample.o  --gen-debug sample.s || exit 1
mips-elf-ld -o sample.elf start.o sample.o /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/mips-elf/10.2.0/libgcc.a -T sample.x || exit 1
mips-elf-objdump -d sample.elf > sample.objdump || exit 1
mips-elf-run sample.elf
