#! /bin/csh -vf

alpha-elf-as -o start.o -g start.S || exit 1
alpha-elf-gcc -o sample.s sample.c -S || exit 1
alpha-elf-as -o sample.o -g sample.s || exit 1
alpha-elf-ld -o sample.elf start.o sample.o -T sample.x || exit 1
alpha-elf-objdump -x -d sample.elf > sample.objdump || exit 1
alpha-elf-run --memory-fill 0xcc --memory-region 0x1e00,0x200 sample.elf
