#! /bin/csh -vf

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG
diff -c gdb-10.2.ppc-elf/sim/common/sim-load.c gdb-10.2.m32c-elf.new/sim/common/sim-load.c > ~/lang/53_GNU_tool/gcc_cross/M32C/memory.diff
diff -c gdb-10.2.ppc-elf/sim/m32c/main.c gdb-10.2.m32c-elf.new/sim/m32c/main.c >> ~/lang/53_GNU_tool/gcc_cross/M32C/memory.diff
diff -c gdb-10.2.ppc-elf/sim/m32c/gdb-if.c gdb-10.2.m32c-elf.new/sim/m32c/gdb-if.c >> ~/lang/53_GNU_tool/gcc_cross/M32C/memory.diff
diff -c gdb-10.2.ppc-elf/sim/m32c/mem.c gdb-10.2.m32c-elf.new/sim/m32c/mem.c >> ~/lang/53_GNU_tool/gcc_cross/M32C/memory.diff
cp -f gdb-10.2.m32c-elf.new/sim/m32c/sim-main.h ~/lang/53_GNU_tool/gcc_cross/M32C/sim-main.h
cp -f gdb-10.2.m32c-elf.new/sim/m32c/r8c.c ~/lang/53_GNU_tool/gcc_cross/M32C/r8c.c
