#! /bin/csh -vf

1750a-elf-as -o start.o -g start.S || exit 1
/media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/gcc-10.2.0.1750a-elf.mine/host-i686-pc-linux-gnu/gcc/cc1 -quiet -o sample.s sample.c || exit 1
1750a-elf-as -o sample.o -g sample.s || exit 1
1750a-elf-ld -o sample.elf start.o sample.o -T sample.x || exit 1
1750a-elf-objdump -x -d -g sample.elf > sample.objdump || exit 1
1750a-elf-run --memory-fill 0xcc --memory-region 0xb000,0x5000 sample.elf
