#! /bin/csh -vxf

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG
cp -f gdb-10.2.rx-elf.new/sim/rx/Makefile.mine ~/lang/53_GNU_tool/gcc_cross/RX/memory/Makefile.mine
cp -f gdb-10.2.rx-elf.new/sim/rx/sim-main.h ~/lang/53_GNU_tool/gcc_cross/RX/memory/sim-main.h
diff -c gdb-10.2.rx-elf{,.new}/sim/common/sim-load.c > ~/lang/53_GNU_tool/gcc_cross/RX/memory/memory.diff
foreach file (gdb-if.c mem.c reg.c rx.c trace.c)
  diff -c gdb-10.2.rx-elf{,.new}/sim/rx/$file >> ~/lang/53_GNU_tool/gcc_cross/RX/memory/memory.diff
end
