all:test003.objdump test003.lof

include ../Makefile.common 

LIBGCC = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/frv-elf/10.2.0/libgcc.a

test003.elf:start.o test003.o

test003.lof:test003.log
