#! /bin/csh -vf

rl78-elf-as -o start.o  -g  start.S || exit 1
rl78-elf-gcc -o sample.s sample.c -S || exit 1
rl78-elf-as -o sample.o  -g sample.s || exit 1
rl78-elf-ld -o sample.elf start.o sample.o /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/rl78-elf/10.2.0/libgcc.a -T sample.x || exit 1
rl78-elf-objdump -x -d sample.elf > sample.objdump || exit 1
#rl78-elf-run sample.elf
rl78-elf-run --memory-fill 0xcc --memory-region 0xf7000,0x1000 sample.elf

