#! /bin/csh -vf

sh64-elf-as -o start.o -g start.S --isa=shmedia || exit 1
/media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/gcc-10.2.0.sh64-elf.mine/host-i686-pc-linux-gnu/gcc/cc1 -quiet -o sample.s sample.c -dAP || exit 1
sh64-elf-as -o sample.o -g sample.s --isa=shmedia || exit 1
sh64-elf-ld -o sample.elf start.o sample.o -T sample.x --oformat elf64-sh64 || exit 1
sh64-elf-objdump -x -d -g sample.elf > sample.objdump || exit 1
setenv USE_SH64_PRINTF
sh64-elf-run --memory-fill 0xcc --memory-region 0x1b000,0x5000 sample.elf
