#! /bin/csh -vf

frv-elf-as -o start.o -g start.S || exit 1
#frv-elf-gcc -o sample.o -g sample.c -c || exit 1
frv-elf-gcc -o sample.s -S sample.c || exit 1
frv-elf-as -o sample.o -g sample.s || exit 1
frv-elf-ld -o sample.elf start.o sample.o /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/frv-elf/10.2.0/libgcc.a -T sample.x || exit 1
frv-elf-objdump -d -x sample.elf > sample.objdump || exit 1
frv-elf-run --memory-fill 0xcc --memory-region 0x1b000,0x5000 sample.elf
