#! /bin/csh -vxf

cp /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/bin/rl78-elf-gdb{.old,}
rl78-elf-gcc -g -o hello.elf hello.c || exit 1
rl78-elf-objdump -x -d hello.elf > hello.objdump || exit 1
wdog.exe -v rl78-elf-gdb -q -x gdbcom.old hello.elf >& hello.log || exit 1
diff hello.log hello.lof.old
