#! /bin/csh -vf

nios2-elf-as -o start.o -g start.S || exit 1
nios2-elf-gcc -o sample.s sample.c -S || exit 1
nios2-elf-as -o sample.o -g sample.s || exit 1
set LIBGCC=/media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/nios2-elf/12.1.0/libgcc.a
nios2-elf-ld -o sample.elf start.o sample.o -T sample.x $LIBGCC || exit 1
nios2-elf-objdump -x -d -g sample.elf > sample.objdump || exit 1
nios2-elf-run --memory-fill 0xcc --memory-region 0x1b000,0x5000 sample.elf
