#! /bin/csh -f

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/

foreach arch (aarch64 arm bfin cr16 cris frv ft32 h8300 iq2000 lm32 m32r m68hc11 mcore microblaze mips mn10300 moxie msp430 or1k pru v850)
	diff -c gdb-10.2.{org,$arch-elf}/gdb/infrun.c > ~/lang/53_GNU_tool/gcc_cross/software-break-point/$arch-elf-swb.diff
end

diff -c gdb-10.2.{org,cris-elf}/sim/cris/cris-tmpl.c >> ~/lang/53_GNU_tool/gcc_cross/software-break-point/cris-elf-swb.diff

diff -c gdb-10.2.{org,lm32-elf}/sim/lm32/lm32.c >> ~/lang/53_GNU_tool/gcc_cross/software-break-point/lm32-elf-swb.diff

diff -c gdb-10.2.{org,m32r-elf}/sim/m32r/m32r.c >> ~/lang/53_GNU_tool/gcc_cross/software-break-point/m32r-elf-swb.diff

diff -c gdb-10.2.{org,moxie-elf}/sim/moxie/interp.c >> ~/lang/53_GNU_tool/gcc_cross/software-break-point/moxie-elf-swb.diff

foreach arch (m32c ppc rl78 sh)
	diff -c gdb-10.2.{org,$arch-elf.new}/gdb/infrun.c > ~/lang/53_GNU_tool/gcc_cross/software-break-point/$arch-elf-swb.diff
end
