#! /bin/csh -f

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/
diff -c gdb-10.2.{org,mn10300-elf}/gdb/infrun.c > ~/lang/53_GNU_tool/gcc_cross/software-break-point/mn10300-elf-swb.diff
diff -c gdb-10.2.{org,mn10300-elf}/gdb/mn10300-tdep.c >> ~/lang/53_GNU_tool/gcc_cross/software-break-point/mn10300-elf-swb.diff
