all:test000.objdump

test000.o:test000.S
	m68hc11-elf-as -o test000.o -g test000.S

test000.elf:test000.o test000.x
	m68hc11-elf-ld -o test000.elf test000.o -T test000.x -Map test000.map

test000.objdump:test000.elf
	m68hc11-elf-objdump -x -d -g test000.elf > test000.objdump
clean:
	rm -f *.o *.elf *.map *.objdump *~
