#! /bin/csh -f

gcc -g -c a.c -o a.o || exit 1
gcc -g3 -c b.c -o b.o || exit 1
gcc -g3 -c c.c -o c.o || exit 1
ar r abc.a a.o b.o c.o || exit 1 
../mktags.exe abc.a || exit 1
diff tags tags.exp || exit 1
../mktags.exe -e abc.a || exit 1
diff TAGS TAGS.e || exit 1


