all:hello.elf hello.objdump

start.o:start.S
	bfin-elf-as -o start.o -g start.S

hello.o:hello.c
	bfin-elf-gcc -o hello.o -g -c hello.c -mcpu=bf522

dummy.o:dummy.c
	bfin-elf-gcc -o dummy.o -g -c dummy.c -mcpu=bf522

DIR0 = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG
DIR1 = $(DIR0)/bfin-elf/lib
DIR2 = $(DIR0)/lib/gcc/bfin-elf/10.2.0

hello.elf:start.o hello.o dummy.o hello.x
	bfin-elf-ld -o hello.elf start.o hello.o dummy.o \
	-L$(DIR1) -lc -L$(DIR2) -lgcc \
	-T hello.x -Map hello.map

hello.objdump:hello.elf
	bfin-elf-objdump -x -d hello.elf > hello.objdump

clean:
	rm -f *.elf *.map *~
