#! /bin/csh -vf

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG
diff -c gdb-10.2.{org,avr-elf}/sim/common/sim-load.c > ~/lang/53_GNU_tool/gcc_cross/AVR/memory.diff
diff -c gdb-10.2.{org,avr-elf}/sim/avr/interp.c >> ~/lang/53_GNU_tool/gcc_cross/AVR/memory.diff
