all:hello.elf hello.objdump 

start.o:start.S
	mcore-elf-as -o start.o -g start.S
	
hello.o:hello.c
	mcore-elf-gcc -o hello.o -g -c hello.c

dummy.o:dummy.c
	mcore-elf-gcc -o dummy.o -g -c dummy.c

DIR = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/mcore-elf/lib

hello.elf:start.o hello.o dummy.o hello.x
	mcore-elf-ld -o hello.elf start.o hello.o dummy.o \
	-T hello.x -Map hello.map -L$(DIR) -lc

hello.objdump:hello.elf
	mcore-elf-objdump -x -t -d hello.elf > hello.objdump

clean:
	rm -f *.o *.elf *.map *.objdump *~

