%.o : %.S
	m68hc11-elf-as -o $@ $< -g

%.o : %.c
	m68hc11-elf-gcc -o $@ $< -c -g

LIBGCC = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/m68hc11-elf/3.4.4/libgcc.a

%.elf : %.o
	m68hc11-elf-ld -o $@ start.o $< $(LIBGCC) -T $(basename $<).x

%.objdump : %.elf
	m68hc11-elf-objdump -x -d -g $< > $@

%.log : %.elf
	wdog.exe -v m68hc11-elf-gdb -q -x gdbcom $< > $@

%.lof : %.log
	wdog.exe -v diff $< $@
	touch $@

clean:
	rm -f *.s *.o *.elf *.objdump *.log *.a *.map *~

