all:test000.elf test000.objdump

test000.o:test000.S
	mcore-elf-as -o test000.o -g test000.S

test000.elf:test000.o test000.x
	mcore-elf-ld -o test000.elf test000.o -T test000.x -Map test000.map

test000.objdump:test000.elf
	mcore-elf-objdump -x -t -d test000.elf > test000.objdump

clean:
	rm -f *.elf *.o *.map *.objdump *~

