#! /bin/csh -f

gcc -g3 a.c -o a.out || exit 1
gcc -g3 b.c -o b.out || exit 1
../mktags.exe a.out b.out || exit 1
diff tags tags.exp || exit 1
../mktags.exe -e a.out b.out || exit 1
diff TAGS TAGS.e || exit 1
