%.o : %.S
	mcore-elf-as -o $@ $< -g

%.o : %.c
	mcore-elf-gcc -o $@ $< -c -g

LIBGCC = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/mcore-elf/10.2.0/libgcc.a

%.elf : %.o
	mcore-elf-ld -o $@ ../default.o $< $(LIBGCC) -T ../default.x

%.objdump : %.elf
	mcore-elf-objdump -x -d -g $< > $@

%.log : %.elf
	wdog.exe -v mcore-elf-gdb -q -x gdbcom $< > $@

%.lof : %.log
	wdog.exe -v diff $< $@
	touch $@

clean:
	rm -f *.s *.o *.elf *.objdump *.log *.a *.map *~

