#! /bin/csh -vxf

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG
diff -c gdb-10.2.{org,cr16-elf}/sim/common/sim-load.c > ~/lang/53_GNU_tool/gcc_cross/CompactRISC/memory/memory.diff
diff -c gdb-10.2.{org,cr16-elf}/sim/cr16/interp.c >> ~/lang/53_GNU_tool/gcc_cross/CompactRISC/memory/memory.diff
cp -f gdb-10.2.cr16-elf/sim/cr16/Makefile ~/lang/53_GNU_tool/gcc_cross/CompactRISC/memory/Makefile.mine
cp -f gdb-10.2.cr16-elf/sim/cr16/mine.cpp ~/lang/53_GNU_tool/gcc_cross/CompactRISC/memory/mine.cpp


