#! /bin/csh -vxf

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/
diff -c gdb-{6.0,10.2}.fr30-elf/sim/fr30/sem-switch.c > ~/lang/53_GNU_tool/gcc_cross/FR30/tool/printf.diff
diff -c gdb-{6.0,10.2}.fr30-elf/sim/fr30/cpu.c >> ~/lang/53_GNU_tool/gcc_cross/FR30/tool/printf.diff
