/home/khasegawa/lang/53_GNU_tool/bbprof/test013.cpp

.br
#include\ <iostream>
.br

.br
int\ main()
.br
\fB{\fR
.br
\fB\ \ using\ namespace\ std;\fR
.br
\fB\ \ cout\ <<\ "hello\ world\\n";\fR
.br
\fB\ \ return\ 0;\fR
.br
\fB}\fR

.br

.br
/usr/local/include/c++/10.2.0/iostream

.br
//\ Standard\ iostream\ objects\ -*-\ C++\ -*-
.br

.br
//\ Copyright\ (C)\ 1997-2020\ Free\ Software\ Foundation,\ Inc.
.br
//
.br
//\ This\ file\ is\ part\ of\ the\ GNU\ ISO\ C++\ Library.\ \ This\ library\ is\ free
.br
//\ software;\ you\ can\ redistribute\ it\ and/or\ modify\ it\ under\ the
.br
//\ terms\ of\ the\ GNU\ General\ Public\ License\ as\ published\ by\ the
.br
//\ Free\ Software\ Foundation;\ either\ version\ 3,\ or\ (at\ your\ option)
.br
//\ any\ later\ version.
.br

.br
//\ This\ library\ is\ distributed\ in\ the\ hope\ that\ it\ will\ be\ useful,
.br
//\ but\ WITHOUT\ ANY\ WARRANTY;\ without\ even\ the\ implied\ warranty\ of
.br
//\ MERCHANTABILITY\ or\ FITNESS\ FOR\ A\ PARTICULAR\ PURPOSE.\ \ See\ the
.br
//\ GNU\ General\ Public\ License\ for\ more\ details.
.br

.br
//\ Under\ Section\ 7\ of\ GPL\ version\ 3,\ you\ are\ granted\ additional
.br
//\ permissions\ described\ in\ the\ GCC\ Runtime\ Library\ Exception,\ version
.br
//\ 3.1,\ as\ published\ by\ the\ Free\ Software\ Foundation.
.br

.br
//\ You\ should\ have\ received\ a\ copy\ of\ the\ GNU\ General\ Public\ License\ and
.br
//\ a\ copy\ of\ the\ GCC\ Runtime\ Library\ Exception\ along\ with\ this\ program;
.br
//\ see\ the\ files\ COPYING3\ and\ COPYING.RUNTIME\ respectively.\ \ If\ not,\ see
.br
//\ <http://www.gnu.org/licenses/>.
.br

.br
/**\ @file\ include/iostream
.br
\ *\ \ This\ is\ a\ Standard\ C++\ Library\ header.
.br
\ */
.br

.br
//
.br
//\ ISO\ C++\ 14882:\ 27.3\ \ Standard\ iostream\ objects
.br
//
.br

.br
#ifndef\ _GLIBCXX_IOSTREAM
.br
#define\ _GLIBCXX_IOSTREAM\ 1
.br

.br
#pragma\ GCC\ system_header
.br

.br
#include\ <bits/c++config.h>
.br
#include\ <ostream>
.br
#include\ <istream>
.br

.br
namespace\ std\ _GLIBCXX_VISIBILITY(default)
.br
{
.br
_GLIBCXX_BEGIN_NAMESPACE_VERSION
.br

.br
\ \ /**
.br
\ \ \ *\ \ @name\ Standard\ Stream\ Objects
.br
\ \ \ *
.br
\ \ \ *\ \ The\ &lt;iostream&gt;\ header\ declares\ the\ eight\ <em>standard\ stream
.br
\ \ \ *\ \ objects</em>.\ \ For\ other\ declarations,\ see
.br
\ \ \ *\ \ http://gcc.gnu.org/onlinedocs/libstdc++/manual/io.html
.br
\ \ \ *\ \ and\ the\ @link\ iosfwd\ I/O\ forward\ declarations\ @endlink
.br
\ \ \ *
.br
\ \ \ *\ \ They\ are\ required\ by\ default\ to\ cooperate\ with\ the\ global\ C
.br
\ \ \ *\ \ library's\ @c\ FILE\ streams,\ and\ to\ be\ available\ during\ program
.br
\ \ \ *\ \ startup\ and\ termination.\ For\ more\ information,\ see\ the\ section\ of\ the
.br
\ \ \ *\ \ manual\ linked\ to\ above.
.br
\ \ */
.br
\ \ //@{
.br
\ \ extern\ istream\ cin;\	\	///\ Linked\ to\ standard\ input
.br
\ \ extern\ ostream\ cout;\	\	///\ Linked\ to\ standard\ output
.br
\ \ extern\ ostream\ cerr;\	\	///\ Linked\ to\ standard\ error\ (unbuffered)
.br
\ \ extern\ ostream\ clog;\	\	///\ Linked\ to\ standard\ error\ (buffered)
.br

.br
#ifdef\ _GLIBCXX_USE_WCHAR_T
.br
\ \ extern\ wistream\ wcin;\	\	///\ Linked\ to\ standard\ input
.br
\ \ extern\ wostream\ wcout;\	///\ Linked\ to\ standard\ output
.br
\ \ extern\ wostream\ wcerr;\	///\ Linked\ to\ standard\ error\ (unbuffered)
.br
\ \ extern\ wostream\ wclog;\	///\ Linked\ to\ standard\ error\ (buffered)
.br
#endif
.br
\ \ //@}
.br

.br
\ \ //\ For\ construction\ of\ filebuffers\ for\ cout,\ cin,\ cerr,\ clog\ et.\ al.
.br
\ \ static\ ios_base::Init\ \fB_\fR_ioinit;

_GLIBCXX_END_NAMESPACE_VERSION
} // namespace

#endif /* _GLIBCXX_IOSTREAM */
