.char \- \N'45'
/home/khasegawa/lang/53_GNU_tool/bbprof/test010.c

.br
#include\ <stdio.h>
.br

.br
#define\ BUFSIZE\ 128
.br
int\ buffer[BUFSIZE];
.br
int\ pointer\ =\ 0;
.br

.br
void\ f(int\ a)
.br
\fB{\fR
.br
\fB\ \ if\ (pointer\ >=\ BUFSIZE)\fR
.br
\fB\ \ \ \ \fRprintf("overflow\\n");
.br
\ \ else
.br
\ \ \ \ buffer[pointer\fB+\fR\fB+]\ =\ a;\fR
.br
\fB}\fR
.br

.br
int\ main()
.br
\fB{\fR
.br
\fB\ \ f(1);\fR
.br
\fB\ \ return\ 0;\fR
.br
\fB}\fR
