.char \- \N'45'
/home/khasegawa/lang/53_GNU_tool/bbprof/test011.c

.br
#include\ <stdio.h>
.br

.br
void\ f()
.br
{
.br
\ \ printf("f\ called\\n");
.br
}
.br

.br
void\ g()
.br
\fB{\fR
.br
\fB\ \ printf("g\ called\\n");\fR
.br
\fB}\fR
.br

.br
void\ h()
.br
\fB{\fR
.br
\fB\ \ printf("h\ called\\n");\fR
.br
\fB}\fR
.br

.br
void\ test(int\ n)
.br
\fB{\fR
.br
\fB\ \ \fR\fBs\fR\fBwitch\ (n)\ {\fR
.br
\ \ case\ 0:
.br
\fB\ \ \ \ \fRf();
.br
\ \ \ \ break;
.br
\ \ case\ 1:
.br
\ \ \ \ \fBg\fR();
.br
\fB\ \ \ \ break;\fR
.br
\ \ case\ 2:
.br
\fB\ \ \ \ \fR\fBh\fR();
.br
\fB\ \ \ \ break;\fR
.br
\ \ default:
.br
\fB\ \ \ \ \fRprintf("default\\n");
.br
\ \ \ \ break;
.br
\ \ }
.br
\fB}\fR
.br

.br
int\ main()
.br
\fB{\fR
.br
\fB\ \ test(2);\fR
.br
\fB\ \ test(1);\fR
.br
\fB\ \ return\ 0;\fR
.br
\fB}\fR
