.char \- \N'45'
/home/khasegawa/lang/53_GNU_tool/bbprof/test026.c

.br
#include\ <setjmp.h>
.br
#include\ <stdio.h>
.br

.br
void\ f(jmp_buf\ env)
.br
\fB{\fR
.br
\fB\ \ \fR\fBl\fRongjmp(env,\ 123);
.br
}
.br

.br
void\ g()
.br
{
.br
}
.br

.br
int\ main()
.br
\fB{\fR
.br
\ \ jmp_buf\ env;
.br
\fB\ \ int\ n\ =\ setjmp(env);\fR
.br
\fB\ \ if\ (n\ ==\ 0)\ {\fR
.br
\fB\ \ \ \ \fR\fBf\fR\fB(env);\fR
.br
\fB\ \ \ \ g();\fR
.br
\ \ }
.br
\ \ else\ {
.br
\fB\ \ \ \ \fR\fBp\fR\fBrintf("setjmp\ returned\ %d\\n",\ n);\fR
.br
\ \ }
.br
\fB\ \ \fR\fBr\fR\fBeturn\ 0;\fR
.br
\fB}\fR
