.char \- \N'45'
/home/khasegawa/lang/53_GNU_tool/bbprof/test022.c

.br
#include\ <stdio.h>
.br

.br
void\ f()
.br
{
.br
\ \ printf("f\ called\\n");
.br
}
.br

.br
void\ g()
.br
\fB{\fR
.br
\fB\ \ printf("g\ called\\n");\fR
.br
\fB}\fR
.br

.br
void\ h(int\ a)
.br
\fB{\fR
.br
\fB\ \ a\ \fR?\ f()\ \fB:\fR\fB\ g();\fR
.br
\fB\ \ \fR\fBp\fR\fBrintf("leave\ `h'\\n");\fR
.br
\fB}\fR
.br

.br
int\ main()
.br
\fB{\fR
.br
\fB\ \ h(0);\fR
.br
\fB\ \ return\ 0;\fR
.br
\fB}\fR
