.char \- \N'45'
/home/khasegawa/lang/53_GNU_tool/bbprof/test023.c

.br
#include\ <stdio.h>
.br

.br
void\ f()
.br
\fB{\fR
.br
\fB\ \ printf("f\ called\\n");\fR
.br
\fB}\fR
.br

.br
void\ g()
.br
{
.br
\ \ printf("g\ called\\n");
.br
}
.br

.br
void\ h(int\ a)
.br
\fB{\fR
.br
\fB\ \ a\ \fR\fB?\fR\fB\ f()\ \fR:\ g();
.br
\ \ \fBp\fR\fBrintf("leave\ `h'\\n");\fR
.br
\fB}\fR
.br

.br
int\ main()
.br
\fB{\fR
.br
\fB\ \ h(1);\fR
.br
\fB\ \ return\ 0;\fR
.br
\fB}\fR
