.char \- \N'45'
/home/khasegawa/lang/53_GNU_tool/bbprof/test006.c

.br
#include\ <stdio.h>
.br

.br
//\ ‹@”\\
.br
int\ function;
.br

.br
int\ f()
.br
\fB{\fR
.br
\fB\	putc('f',\ stdout);\ \fR
.br
\fB\	putc('\\n',\ stdout);\ \fR
.br
\fB\	return\ 2;\fR
.br
\fB}\fR
.br

.br
int\ g()
.br
{
.br
\ \ return\ function\ +\ 3;
.br
}
.br

.br
int\ h(int\ a)
.br
\fB{\fR
.br
\fB\ \ return\ a\ \fR\fB?\fR\fB\ f()\ \fR:\ g();
.br
\fB}\fR
.br

.br
int\ main()
.br
\fB{\fR
.br
\fB\ \ printf("%d\\n",\ h(1));\fR
.br
\fB\ \ return\ 0;\fR
.br
\fB}\fR
