.char \- \N'45'
/home/khasegawa/lang/53_GNU_tool/bbprof/test021.cpp

.br
#include\ <stdio.h>
.br

.br
void\ f()
.br
\fB{\fR
.br
\fB\ \ throw\ \fR\fB"\fRHelp!";
.br
}
.br

.br
void\ g()
.br
{
.br
}
.br

.br
int\ main()
.br
\fB{\fR
.br
\ \ try\ {
.br
\fB\ \ \ \ f();\fR
.br
\fB\ \ \ \ g\fR();
.br
\ \ }\ \fBc\fR\fBatch\ (const\ char*\ \fRp)\ {
.br
\ \ \ \ puts\fB(\fRp);
.br
\ \ }
.br
\fB\ \ \fR\fBr\fR\fBeturn\ 0;\fR
.br
\fB}\fR
