.char \- \N'45'
/home/khasegawa/lang/53_GNU_tool/bbprof/test014.cpp

.br
#include\ <stdio.h>
.br

.br
struct\ X\ {
.br
\ \ \fBX\fR\fB()\fR
.br
\ \ {
.br
\fB\ \ \ \ printf("X::X()\ called\\n");\fR
.br
\fB\ \ \fR\fB}\fR
.br
\ \ \fB~\fR\fBX()\fR
.br
\ \ {
.br
\fB\ \ \ \ printf("X::~X()\ called\\n");\fR
.br
\fB\ \ \fR\fB}\fR
.br
};
.br

.br
X\ \fBo\fRbj;
.br

.br
int\ main()
.br
\fB{\fR
.br
\fB\ \ printf("main\ called\\n");\fR
.br
\fB\ \ return\ 0;\fR
.br
\fB}\fR
