#! /bin/csh -f

foreach file ( test00[0-9].c test01[0-2].c test01[345].cpp test01[6-9].c \
	       test020.c test02[23].c test02[45].cpp \
	       test02[67].c test02[89].cpp test03[01].c test03[23].cpp \
	       test034.c test035.cpp test036.c test037.cpp test038.c \
	       test039.cpp test040.cpp test041.cpp \
	       test021.cpp )
	csh -f verif $file || echo "error at $file"
end

echo "ok"
