#! /bin/csh -f

foreach file ( test00[0-9].c test01[0-2].c test01[345].cpp test01[6-9].c \
	       test020.c test021.cpp test02[23].c test02[45].cpp \
	       test02[67].c test02[89].cpp test03[01].c test03[23].cpp )
	csh -f verif $file || exit 1
end

echo "ok"
