%.o : %.S
	hppa-elf-as -o $@ -g $<

%.o : %.c
	hppa-elf-gcc -o $@ $< -g -c

%.elf : %.o 
	hppa-elf-ld -o $@ ../default.o $< -T ../default.x

%.objdump : %.elf
	hppa-elf-objdump -x -d -g $< > $@

%.log : %.elf
	wdog.exe -v hppa-elf-gdb -q -x gdbcom $< > $@

%.lof : %.log
	wdog.exe -v diff $< $@
	touch $@

clean:
	rm -f *.o *.s *.elf *.map *.objdump *.objcopy *.log TAGS *~
