#! /bin/csh -vf

aarch64-elf-as -o start.o -g start.S || exit 1
aarch64-elf-gcc -o sample.s -S sample.c || exit 1
aarch64-elf-as -o sample.o -g sample.s || exit 1
aarch64-elf-ld -o sample.elf start.o sample.o /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/aarch64-elf/10.2.0/libgcc.a -T sample.x || exit 1
aarch64-elf-objdump -d sample.elf > sample.objdump || exit 1
#aarch64-elf-run sample.elf
aarch64-elf-run --memory-region 0xe000,0x1000 sample.elf

