#! /bin/csh -vf

aarch64-elf-as -o start.o -g start.S || exit 1
aarch64-elf-gcc -o test020.o -g test020.c -c || exit 1
aarch64-elf-ld -o test020.elf start.o test020.o /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/lib/gcc/aarch64-elf/10.2.0/libgcc.a -T test020.x || exit 1
aarch64-elf-objdump -d test020.elf > test020.objdump || exit 1
aarch64-elf-run test020.elf
