#! /bin/csh -f

cd /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG
diff -c gdb-6.0.d30v-elf/sim/d30v/engine.c gdb-10.2.d30v-elf/sim/d30v/engine.c  > ~/lang/53_GNU_tool/gcc_cross/D30V/tool/printf.diff
