#! /bin/csh -f

cp /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/bin/ft32-elf-gdb{.new,}
cp /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/bin/ft32-elf-run{.new,}
cp ~/lang/53_GNU_tool/gcc_cross/FT32/tool/sample.x{.new,}
cp ~/lang/53_GNU_tool/gcc_cross/FT32/tool/start.S{.new,}

