#! /bin/csh -f

cp /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/bin/ft32-elf-gdb{.old,}
cp /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/bin/ft32-elf-run{.old,}
cp ~/lang/53_GNU_tool/gcc_cross/FT32/tool/sample.x{.old,}
cp ~/lang/53_GNU_tool/gcc_cross/FT32/tool/start.S{.old,}
cp ~/lang/53_GNU_tool/gcc_cross/FT32/tool/start.o{.old,}
cp gdbcom{.old,}
cp start.S{.old,}
cp hello.x{.old,}
cp ../test002/gdbcom{.old,}
cp ../test002/start.S{.old,}
cp ../test002/test002.lof{.old,}
cp ../test002/test002.x{.old,}
