#! /bin/csh -vf

z8k-coff-as -o start.o -g start.S || exit 1
/media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/gcc-3.4.4.z8k-coff/gcc/cc1 -quiet -o sample.s sample.c || exit 1
z8k-coff-as -o sample.o sample.s -g || exit 1
z8k-coff-ld -o sample.coff start.o sample.o -T sample.x || exit 1
z8k-coff-objdump -x -d sample.coff > sample.objdump || exit 1
z8k-coff-run --memory-fill 0xcc --memory-region 0x0e00,0x200 sample.coff
