#! /bin/csh -vf

vax-elf-as -o start.o -g start.S || exit 1
vax-elf-gcc -o sample.s sample.c -S || exit 1
vax-elf-as -o sample.o -g sample.s || exit 1
#vax-elf-gcc -o sample.o sample.c -g -c || exit 1
vax-elf-ld -o sample.elf start.o sample.o -T sample.x || exit 1
vax-elf-objdump -x -d sample.elf > sample.objdump || exit 1
vax-elf-run --memory-fill 0xcc --memory-region 0xeffc,0x1000 sample.elf
