LIBQ = libqemu.a
LIBS = libsim.a

all:$(LIBQ) $(LIBS) crt0.o

VPATH = ../../../../libgloss/moxie ../../../../libgloss/moxie/..

%.o : %.c
	moxie-elf-gcc -o $@ $< -c -g -I../../../../libgloss

%.o : %.S
	moxie-elf-as -o $@ $< -g


QOBJS = qemu-write.o \
	qemu-time.o \
	sim-exit.o \
	sbrk.o \
	sim-close.o \
	fstat.o \
	getpid.o \
	isatty.o \
	kill.o \
	putnum.o \
	sim-lseek.o \
	sim-read.o \

	
$(LIBQ):$(QOBJS)
	rm -f $@
	ar rc $@ $(QOBJS)

SOBJS = fstat.o \
	getpid.o \
	isatty.o \
	kill.o \
	putnum.o \
	sbrk.o \
	sim-close.o \
	sim-exit.o \
	sim-inbyte.o \
	sim-lseek.o \
	sim-open.o \
	sim-read.o \
	sim-time.o \
	sim-unlink.o \
	sim-write.o \
	stat.o \


$(LIBS):$(SOBJS)
	rm -f $@
	ar rc $@ $(SOBJS)

clean:
	rm -f $(LIBQ) $(QOBJS) $(LIBS) $(SOBJS) crt0.o
