all:hello.objdump

start.o:start.S
	bpf-as -o start.o -g start.S

#hello.o:hello.s
#	bpf-as -o hello.o -g -c hello.s
#
#hello.s:hello.c
#	bpf-gcc -o hello.s -S hello.c -D__IEEE_LITTLE_ENDIAN

hello.o:hello.c
	bpf-gcc -o hello.o -g -c hello.c -D__IEEE_LITTLE_ENDIAN

dummy.o:dummy.c
	bpf-gcc -o dummy.o -g -c dummy.c -D__IEEE_LITTLE_ENDIAN

DIR = /media/ca850f52-0605-42a7-9fd4-899de9edf461/work/GNU_LANG/bpf/lib

hello.elf:start.o hello.o dummy.o hello.x
	bpf-ld -o hello.elf start.o hello.o dummy.o \
	-L$(DIR) -lc -T hello.x -Map hello.map

hello.objdump:hello.elf
	bpf-objdump -x -t -s -d hello.elf > hello.objdump

clean:
	rm -f *.o *.elf *.map *.objdump *~

