#! /bin/csh -f

cp a.c.org a.c || exit 1
gcc -g3 a.c b.c -o a.out || exit 1
rm -f a.c || exit 1
../mktags.exe -E /usr a.out >& mktags.log || exit 1
diff mktags.log mktags.lof || exit 1
diff tags tags.exp || exit 1
../mktags.exe -e -E /usr a.out >& mktags.log || exit 1
diff mktags.log mktags.lof || exit 1
diff TAGS TAGS.e || exit 1
