#! /bin/csh -f

gcc -g3 dir/a.c -c -o dir/a.o || exit 1
gcc -g3 b.c -c -o b.o || exit 1
gcc dir/a.o b.o -o a.out || exit 1
../mktags.exe a.out || exit 1
diff tags tags.exp || exit 1
../mktags.exe -e a.out || exit 1
diff TAGS TAGS.e || exit 1
